import { PrismaClient } from '../src/generated/prisma';
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  // Password for all demo users (hashed)
  const password = await bcrypt.hash("tennis123", 10);

  await prisma.player.createMany({
    data: [
      {
        username: 'julius',
        email: 'federer@pwani.ac.ke',
        phone: '0700000001',
        passwordHash: password,
        firstName: 'julius',
        lastName: 'nyerere',
        photo: '/images/federer.jpg',
        gender: 'Male',
        dateOfBirth: new Date('1981-08-08'),
        nationality: 'Switzerland',
        bio: '20-time Grand Slam champion.',
        matchesPlayed: 0,
        matchesRefereed: 0,
        matchesBallCrew: 0,
        matchesWon: 0,
        matchesLost: 0,
      },
      {
        username: 'joe',
        email: 'nadal@pwani.ac.ke',
        phone: '0700000002',
        passwordHash: password,
        firstName: 'joe',
        lastName: 'kazungu',
        photo: '/images/nadal.jpg',
        gender: 'Male',
        dateOfBirth: new Date('1986-06-03'),
        nationality: 'Spain',
        bio: 'King of Clay.',
        matchesPlayed: 0,
        matchesRefereed: 0,
        matchesBallCrew: 0,
        matchesWon: 0,
        matchesLost: 0,
      },
      {
        username: 'leah',
        email: 'djokovic@pwani.ac.ke',
        phone: '0700000003',
        passwordHash: password,
        firstName: 'leah',
        lastName: 'crush',
        photo: '/images/djokovic.jpg',
        gender: 'female',
        dateOfBirth: new Date('1987-05-22'),
        nationality: 'Serbia',
        bio: 'Serbian tennis legend.',
        matchesPlayed: 0,
        matchesRefereed: 0,
        matchesBallCrew: 0,
        matchesWon: 0,
        matchesLost: 0,
      },
      {
        username: 'winnie',
        email: 'serena@pwani.ac.ke',
        phone: '0700000004',
        passwordHash: password,
        firstName: 'winnie',
        lastName: 'mueni',
        photo: '/images/williams.jpg',
        gender: 'Female',
        dateOfBirth: new Date('1981-09-26'),
        nationality: 'USA',
        bio: 'Greatest women\'s player.',
        matchesPlayed: 0,
        matchesRefereed: 0,
        matchesBallCrew: 0,
        matchesWon: 0,
        matchesLost: 0,
      },
      {
        username: 'wilfred',
        email: 'sharapova@pwani.ac.ke',
        phone: '0700000005',
        passwordHash: password,
        firstName: 'wilfred',
        lastName: 'kimani',
        photo: '/images/sharapova.jpg',
        gender: 'male',
        dateOfBirth: new Date('1987-04-19'),
        nationality: 'Russia',
        bio: 'Siberian Siren.',
        matchesPlayed: 0,
        matchesRefereed: 0,
        matchesBallCrew: 0,
        matchesWon: 0,
        matchesLost: 0,
      },
      {
        username: 'peter',
        email: 'murray@pwani.ac.ke',
        phone: '0700000006',
        passwordHash: password,
        firstName: 'peter',
        lastName: 'mwangi',
        photo: '/images/murray.jpg',
        gender: 'Male',
        dateOfBirth: new Date('1987-05-15'),
        nationality: 'UK',
        bio: 'Scottish tennis star.',
        matchesPlayed: 0,
        matchesRefereed: 0,
        matchesBallCrew: 0,
        matchesWon: 0,
        matchesLost: 0,
      },
      {
        username: 'morris',
        email: 'murray1@pwani.ac.ke',
        phone: '0700000006',
        passwordHash: password,
        firstName: 'morris',
        lastName: 'morris',
        photo: '/images/murray.jpg',
        gender: 'Male',
        dateOfBirth: new Date('1987-05-15'),
        nationality: 'UK',
        bio: 'Scottish tennis star.',
        matchesPlayed: 0,
        matchesRefereed: 0,
        matchesBallCrew: 0,
        matchesWon: 0,
        matchesLost: 0,
      },
      {
        username: 'jojo',
        email: 'murray2@pwani.ac.ke',
        phone: '0700000006',
        passwordHash: password,
        firstName: 'jojo',
        lastName: 'jbouy',
        photo: '/images/murray.jpg',
        gender: 'Male',
        dateOfBirth: new Date('1987-05-15'),
        nationality: 'UK',
        bio: 'Scottish tennis star.',
        matchesPlayed: 0,
        matchesRefereed: 0,
        matchesBallCrew: 0,
        matchesWon: 0,
        matchesLost: 0,
      },
    ],
    skipDuplicates: true,
  });

  console.log('Seeded 8 players with full details!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });